{% set name = "cppyy" %}
{% set version = "1.8.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cppyy/cppyy-{{ version }}.tar.gz
  sha256: 5d0d0533bc0ff3645cbd58a97d13ec3d284fb87d2183b6ba7d8852c5409b6546
  patches:
    - 0001-dumb-setup.py.patch
    - add_default_paths_on_pypy.diff

build:
  number: 1
  skip: true  # [win]
  # Upstream does not properly support our version of PyPy. This should change
  # beyond 1.8.3, see
  # https://github.com/conda-forge/cppyy-feedstock/pull/30#issuecomment-693463465.
  skip: true  # [python_impl=="pypy"]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  detect_binary_files_with_prefix: false

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cppyy-backend ==1.14.0
  run:
    - python
    - cpycppyy ==1.11.4  # [python_impl=="cpython"]
    - cppyy-backend ==1.14.0

test:
  requires:
    - gmp
  imports:
    - cppyy
  commands:
    - $PYTHON -c 'import cppyy;V = cppyy.gbl.std.vector[int]();V.push_back(1)'
    - $PYTHON -c 'import cppyy;cppyy.load_library("gmp")'
    - $PYTHON -c 'import cppyy;cppyy.include("gmp.h")'

about:
  home: https://pypi.org/project/cppyy/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python-C++ bindings interface based on Cling/LLVM
  description: |
    An automatic Python-C++ bindings generator, for calling C++ from Python and
    Python from C++, designed for large scale programs in high performance
    computing that use modern C++. 
  doc_url: http://cppyy.readthedocs.io/
  dev_url: https://bitbucket.org/wlav/cppyy/src

extra:
  recipe-maintainers:
    - saraedum
    - isuruf
