{% set version = "3.5.0" %}

package:
  name: cppyy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cppyy/cppyy-{{ version }}.tar.gz
  sha256: b9cfd48bd0c6e0c7399a82cca2105d7d90699adb3083904aaf30bf3632224e79
  patches:
    - patches/0001-do-not-rebuild-allDict.patch

build:
  number: 0
  skip: true  # [win]
  # compiler flags set by cppyy-cling do not work on aarch64, https://github.com/conda-forge/cppyy-cling-feedstock/pull/52
  skip: true  # [aarch64]
  # ppc64 build fails with
  # "IncrementalExecutor::executeFunction: symbol 'DW.ref.__gxx_personality_v0' unresolved while linking [cling interface function]!"
  # It's not clear what's the problem.
  skip: true  # [ppc64le]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  detect_binary_files_with_prefix: false

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    # cppyy-cling, cppyy-backend, cpycppyy and cppyy are essentially a single package, so we always pin exactly between these.
    - cpycppyy ==1.13.0
    # cppyy-cling, cppyy-backend, cpycppyy and cppyy are essentially a single package, so we always pin exactly between these.
    - cppyy-backend ==1.15.3
    # cppyy-cling, cppyy-backend, cpycppyy and cppyy are essentially a single package, so we always pin exactly between these.
    - cppyy-cling ==6.32.8
  run:
    - python
    # cppyy-cling, cppyy-backend, cpycppyy and cppyy are essentially a single package, so we always pin exactly between these.
    - cpycppyy ==1.13.0
    # cppyy-cling, cppyy-backend, cpycppyy and cppyy are essentially a single package, so we always pin exactly between these.
    - cppyy-backend ==1.15.3
    # cppyy-cling, cppyy-backend, cpycppyy and cppyy are essentially a single package, so we always pin exactly between these.
    - cppyy-cling ==6.32.8

test:
  requires:
    - gmp
  imports:
    - cppyy
  commands:
    - $PYTHON -c 'import cppyy;V = cppyy.gbl.std.vector[int]();V.push_back(1)'
    - $PYTHON -c 'import cppyy;cppyy.load_library("gmp")'
    - $PYTHON -c 'import cppyy;cppyy.include("gmp.h")'

about:
  home: https://pypi.org/project/cppyy/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python-C++ bindings interface based on Cling/LLVM
  description: |
    An automatic Python-C++ bindings generator, for calling C++ from Python and
    Python from C++, designed for large scale programs in high performance
    computing that use modern C++. 
  doc_url: http://cppyy.readthedocs.io/
  dev_url: https://github.com/wlav/cppyy

extra:
  recipe-maintainers:
    - saraedum
    - isuruf
