{% set name = "cppyy" %}
{% set version = "1.5.3" %}

package:
  name: {{ name  }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cppyy/cppyy-{{ version   }}.tar.gz
  sha256: 9d5826b1c7cd2ced7caf773ca23a6f044cccc5c2709459dc1654cda04463475c

build:
  number: 0
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv --install-option=--force-bdist"
  detect_binary_files_with_prefix: False

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cppyy-backend
    - cpycppyy
  run:
    - python
    - cpycppyy

test:
  imports:
    - cppyy
  commands:
    - $PYTHON -c 'import cppyy;V = cppyy.gbl.std.vector[int]();V.push_back(1)'

about:
  home: https://pypi.org/project/cppyy/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Python-C++ bindings interface based on Cling/LLVM'
  description: |
    An automatic Python-C++ bindings generator, for calling C++ from Python and
    Python from C++, designed for large scale programs in high performance
    computing that use modern C++. 
  doc_url: http://cppyy.readthedocs.io/
  dev_url: https://bitbucket.org/wlav/cppyy/src

extra:
  recipe-maintainers:
    - saraedum
    - isuruf
