{% set name = "cppyy" %}
{% set version = "2.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cppyy/cppyy-{{ version }}.tar.gz
  sha256: 24be84c676f020c800c803abfc3a15268bd80f1b898fda41d3169b236c16b235
  patches:
    - add_default_paths_on_pypy.patch
    - alldict.patch

build:
  number: 0
  skip: true  # [win]
  # cppyy is broken on ppc: https://github.com/conda-forge/cppyy-feedstock/issues/55
  skip: true  # [ppc64le]
  # compiler flags set by cppyy-cling do not work on aarch64, https://github.com/conda-forge/cppyy-cling-feedstock/pull/52
  skip: true  # [aarch64]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  detect_binary_files_with_prefix: false

requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    # cppyy-cling, cppyy-backend, cpycppyy and cppyy are essentially a single package, so we always pin exactly between these.
    - cppyy-backend ==1.14.9
  run:
    - python
    # cppyy-cling, cppyy-backend, cpycppyy and cppyy are essentially a single package, so we always pin exactly between these.
    - cpycppyy ==1.12.11  # [python_impl=="cpython"]
    # cppyy-cling, cppyy-backend, cpycppyy and cppyy are essentially a single package, so we always pin exactly between these.
    - cppyy-backend ==1.14.9

test:
  requires:
    - gmp
  imports:
    - cppyy
  commands:
    - $PYTHON -c 'import cppyy;V = cppyy.gbl.std.vector[int]();V.push_back(1)'
    - $PYTHON -c 'import cppyy;cppyy.load_library("gmp")'
    - $PYTHON -c 'import cppyy;cppyy.include("gmp.h")'

about:
  home: https://pypi.org/project/cppyy/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python-C++ bindings interface based on Cling/LLVM
  description: |
    An automatic Python-C++ bindings generator, for calling C++ from Python and
    Python from C++, designed for large scale programs in high performance
    computing that use modern C++. 
  doc_url: http://cppyy.readthedocs.io/
  dev_url: https://bitbucket.org/wlav/cppyy/src

extra:
  recipe-maintainers:
    - saraedum
    - isuruf
