{% set name = "cppyy" %}
{% set version = "1.5.0" %}

package:
  name: {{ name  }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cppyy/cppyy-{{ version   }}.tar.gz
  sha256: aa1f3ceccd7df8d4006992aa6f9e359a63829ab628128bc74d55bcebec75b342
  patches:
  - manylinux.patch

build:
  number: 0
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  detect_binary_files_with_prefix: False

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cppyy-backend
  run:
    - python
    - cpycppyy

test:
  imports:
    - cppyy
  commands:
    - $PYTHON -c 'import cppyy;V = cppyy.gbl.std.vector[int]();V.push_back(1)'

about:
  home: https://pypi.org/project/cppyy/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Python-C++ bindings interface based on Cling/LLVM'
  description: |
    An automatic Python-C++ bindings generator, for calling C++ from Python and
    Python from C++, designed for large scale programs in high performance
    computing that use modern C++. 
  doc_url: http://cppyy.readthedocs.io/
  dev_url: https://bitbucket.org/wlav/cppyy/src

extra:
  recipe-maintainers:
    - saraedum
    - isuruf
