# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.14
  strategy:
    matrix:
      3.6_73_pypy:
        CONFIG: osx_3.6_73_pypy
        UPLOAD_PACKAGES: 'True'
      3.6_cpython:
        CONFIG: osx_3.6_cpython
        UPLOAD_PACKAGES: 'True'
      3.7_cpython:
        CONFIG: osx_3.7_cpython
        UPLOAD_PACKAGES: 'True'
      3.8_cpython:
        CONFIG: osx_3.8_cpython
        UPLOAD_PACKAGES: 'True'
    maxParallel: 8
  timeoutInMinutes: 360

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)